### PR TITLE
Switch the default options for EpsilonConstraint

### PR DESCRIPTION
**Pull request by odow**
@xgandibleux is this better?

It'd mean in your JuMP examples you could just use
```
set_optimizer_attribute(model, MOA.Algorithm(), MOA.EpsilonConstraint())
```
instead of 
```
set_optimizer_attribute(model, MOA.Algorithm(), MOA.EpsilonConstraint())
set_optimizer_attribute(model, MOA.ObjectiveAbsoluteTolerance(1), 1)
```

### CODE REVIEW

**Comment by xgandibleux** [comment]
Indeed. The step value of 1 is usual for $\epsilon$. Thus, setting it as default value is fine, and letting to the user the possibility to setup the algorithm with a non-negative float value via the parameter (preferably named e.g. "step", "stepForEpsilon" than "tolerance" which evokes possible precision problems, or approximate solutions).

**Comment by odow** [comment]
> or approximate solutions

But isn't this exactly what is happening? If I set the `ObjectiveAbsoluteTolerance` to `2.0` in an integer problem, then I might miss solutions. (The complication being that they can be out by at most that tolerance / 2.)

There's definitely a trade-off. We could either introduce lots of algorithm-specific options, or try to re-use common names, even if they're slightly clunky.

Would `EpsilonConstraintStep()` be a better option?

**Comment by xgandibleux** [comment]
`EpsilonConstraintStep()`is perfect.

**Comment by xgandibleux** [comment]
I was not fan of `tolerance` since it evokes a parameter to deal with numerical approximations (resulting e.g. from the MIP resolution). 

But you are right. With $\epsilon$=2 the algorithm may miss non dominated points (and we encounter some uses of this algorithm where the value of $\epsilon$ is dynamically tuned, e.g. when a timeout limit is taking into account, which is not into in the version available here, and somewhere not relevant to be coded I think because specific to a problem and outputs expected).

**Pull request merged**
