### PR TITLE
Support MOI.TimeLimitSec

### PR DESCRIPTION
**Pull request by odow**
Closes #53

### CODE REVIEW

**Comment by remi-garcia** [comment]
Thank you for adding that support so fast!

Just a few question:
- do you confirm that if I set a time limit of 10s and the first optimization takes 60s then it will not stop after 10s but after the first optimization?
- the compilation time of the first `optimize!` will count in the solving time?

**Comment by odow** [comment]
> do you confirm that if I set a time limit of 10s and the first optimization takes 60s then it will not stop after 10s but after the first optimization?

Correct. This often happens, even with MILP solvers. They solve the root, then check time limit. If your time limit cannot even solve a single scalar problem, then it can't solve a multi-objective problem either...

> the compilation time of the first optimize! will count in the solving time?

No. It only times once the optimize method actually starts running. We can't time the latency that the user experiences.

**Comment by odow** [comment]
> Here I believe it could be an issue. It could lead to a really large overhead if each solution takes minutes to be obtained.
For example, if the last optimize! starts just before the time limit and takes 5 minutes it does not seem normal to stop after 15 minutes if the time limit was 10 minutes.

I think this is a pretty standard use of time limit, but it shouldn't be too hard to pass the time limit to the solver if supported. Let me take a look. 

```Julia
start_time = time()
optimize!(model)
println(time() - start_time)
```

So here you're timing in user-land how long that took, which you can do. But inside `optimize!`, we can't time how long it took to compile.

**Comment by remi-garcia** [comment]
> I think this is a pretty standard use of time limit, but it shouldn't be too hard to pass the time limit to the solver if supported. Let me take a look.

I had a discussion on this topic yesterday and it was mentioned that, for some algorithms in some cases, many solutionns are obtained quickly and then one optimization could take hours (in particular to prove infeasibility). I think #55 is important to avoid that.


> So here you're timing in user-land how long that took, which you can do. But inside optimize!, we can't time how long it took to compile.

Oh! I forgot that `optimize!` is already called before and compiled. Thank you for the precision.
Is there any reason to avoid using `solve_time` instead of `time`?

**Pull request merged**
